import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from difflib import SequenceMatcher

nltk.download('punkt')
nltk.download('stopwords')

responses = {
    "boa noite": "Boa noite!",
    "boa tarde": "Boa tarde!",
    "bom dia": "Bom dia!",
    "byte boa tarde": "Boa tarde!",
    "byte bom dia": "Bom dia!",
    "byte como esta voce": "Bem",
    "byte como esta": "Eu estou bem",
    "byte como vai voce": "Bem",
    "byte como vai": "Eu estou bem",
    "byte e ai amigo": "E ai, como vai você?",
    "byte e ai beleza": "Beleza",
    "byte e ai cara": "Tudo bom?",
    "byte e ai como esta": "Bem",
    "byte e ai como vai": "Bem",
    "byte e ai irmao": "E ai, como vai você?",
    "byte e ai mano": "E ai, como vai você?",
    "byte e ai mano": "Tudo bom?",
    "byte e um prazer te conhecer": "Obrigado. Você também",
    "byte eai": "Eai, como vai?",
    "byte esta tudo bem": "Melhor agora",
    "byte oi": "Olá!",
    "byte oii": "Olá!",
    "byte oiii": "Olá!",
    "byte ola": "Oi!",
    "byte olaa": "Oi!",
    "byte olaaa": "Oi!",
    "byte opa": "Olá!",
    "byte prazer em conhecelo": "Obrigado, digo o mesmo",
    "byte quanto tempo": "Como vai?",
    "byte salve": "Salve!",
    "byte saudacoes": "Olá!",
    "byte ta tudo bem": "Melhor agora",
    "byte td bem": "Tudo, e você?",
    "byte td bom": "Melhor agora",
    "byte tudo bem": "Melhor agora",
    "byte tudo bom": "Melhor agora",
    "byte tudo de bom e voce": "Tudo bem",
    "byte vou bem": "Que ótimo!",
    "como esta voce": "Bem",
    "como esta": "Eu estou bem",
    "como vai voce": "Bem",
    "como vai": "Eu estou bem",
    "e ai amigo": "E ai, como vai você?",
    "e ai beleza": "Beleza",
    "e ai cara": "Tudo bom?",
    "e ai como esta": "Bem",
    "e ai como vai": "Bem",
    "e ai irmao": "E ai, como vai você?",
    "e ai mano": "E ai, como vai você?",
    "e ai mano": "Tudo bom?",
    "e um prazer te conhecer": "Obrigado. Você também",
    "eai": "Eai, como vai?",
    "esta tudo bem": "Melhor agora",
    "oi": "Olá!",
    "oii": "Olá!",
    "oiii": "Olá!",
    "ola": "Oi!",
    "olaa": "Oi!",
    "olaaa": "Oi!",
    "opa": "Olá!",
    "prazer em conhecelo": "Obrigado, digo o mesmo",
    "quanto tempo": "Como vai?",
    "robo boa tarde": "Boa tarde!",
    "robo bom dia": "Bom dia!",
    "robo como esta voce": "Bem",
    "robo como esta": "Eu estou bem",
    "robo como vai voce": "Bem",
    "robo como vai": "Eu estou bem",
    "robo e ai amigo": "E ai, como vai você?",
    "robo e ai beleza": "Beleza",
    "robo e ai cara": "Tudo bom?",
    "robo e ai como esta": "Bem",
    "robo e ai como vai": "Bem",
    "robo e ai irmao": "E ai, como vai você?",
    "robo e ai mano": "E ai, como vai você?",
    "robo e ai mano": "Tudo bom?",
    "robo e um prazer te conhecer": "Obrigado. Você também",
    "robo eai": "Eai, como vai?",
    "robo esta tudo bem": "Melhor agora",
    "robo oi": "Olá!",
    "robo oii": "Olá!",
    "robo oiii": "Olá!",
    "robo ola": "Oi!",
    "robo olaa": "Oi!",
    "robo olaaa": "Oi!",
    "robo opa": "Olá!",
    "robo prazer em conhecelo": "Obrigado, digo o mesmo",
    "robo quanto tempo": "Como vai?",
    "robo salve": "Salve!",
    "robo saudacoes": "Olá!",
    "robo ta tudo bem": "Melhor agora",
    "robo td bem": "Tudo, e você?",
    "robo td bom": "Melhor agora",
    "robo tudo bem": "Melhor agora",
    "robo tudo bom": "Melhor agora",
    "robo tudo de bom e voce": "Tudo bem",
    "robo vou bem": "Que ótimo!",
    "salve": "Salve!",
    "saudacoes": "Olá!",
    "ta tudo bem": "Melhor agora",
    "td bem": "Tudo, e você?",
    "td bom": "Melhor agora",
    "tudo bem": "Melhor agora",
    "tudo bom": "Melhor agora",
    "tudo de bom e voce": "Tudo bem",
    "vou bem": "Que ótimo!",
    "eai amigo": "E ai, como vai você?",
    "eai beleza": "Beleza",
    "eai cara": "Tudo bom?",
    "eai como esta": "Bem",
    "eai como vai": "Bem",
    "eai irmao": "E ai, como vai você?",
    "eai mano": "E ai, como vai você?",
    "eai mano": "Tudo bom?",
    "bem": "que bom",
    "bom": "que bom",
    "estou bem": "que bom",
    "estou bom": "que bom",
    "com q vc trabalha": "Eu trabalho te ajudando.",
    "com q voce trabalha": "Eu trabalho te ajudando.",
    "com que vc trabalha": "Eu trabalho te ajudando.",
    "com que voce trabalha": "Eu trabalho te ajudando.",
    "como chama vc": "Meu nome é Byte",
    "como chama voce": "Meu nome é Byte",
    "como q vc chama": "Meu nome é Byte",
    "como q vc se chama": "Meu nome é Byte",
    "como q voce chama": "Meu nome é Byte",
    "como q voce se chama": "Meu nome é Byte",
    "como que vc chama": "Meu nome é Byte",
    "como que vc se chama": "Meu nome é Byte",
    "como que voce chama": "Meu nome é Byte",
    "como que voce se chama": "Meu nome é Byte",
    "como se chama": "Meu nome é Byte",
    "como vc se chama": "Meu nome é Byte",
    "como vc trabalha": "Eu trabalho te ajudando.",
    "como voce se chama": "Meu nome é Byte",
    "como voce trabalha": "Eu trabalho te ajudando.",
    "qual a sua idade": "Tenho menos anos do que pareco ter, e mais do que um dia já tive. ",
    "qual e seu nome": "Meu nome é Byte",
    "qual que e seu nome": "Meu nome é Byte",
    "qual seu nome": "Meu nome é Byte",
    "qual sua idade": "Tenho menos anos do que pareco ter, e mais do que um dia já tive. ",
    "quantos anos tens": "Tenho menos do que pareco ter, e mais do que um dia já tive. ",
    "quantos anos voce tem": "Tenho menos do que pareco ter, e mais do que um dia já tive. ",
    "quem e voce": "Sou o Byte, um robô criado para te ajudar",
    "sua idade": "Tenho menos anos do que pareco ter, e mais do que um dia já tive. ",
    "vc trabalha como": "Eu trabalho te ajudando.",
    "vc trabalha": "Eu trabalho te ajudando.",
    "voce trabalha": "Eu trabalho te ajudando.",
    "o que voce faz": "Eu te ajudo",
    "voce faz o que": "Eu te ajudo",
    "como trabalha": "Eu te ajudo",
    "voce trabalha como": "Eu trabalho te ajudando.",
    "voce trabalha": "Eu trabalho te ajudando.",
    "acha que chovera amanha": "execute_action{weather(forecast_tomorrow)}",
    "acha que chovera depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "acha que chovera hoje": "execute_action{weather(forecast_today)}",
    "acha que fara sol amanha": "execute_action{weather(forecast_tomorrow)}",
    "acha que fara sol depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "acha que fara sol hoje": "execute_action{weather(forecast_today)}",
    "acha que nevara amanha": "execute_action{weather(forecast_tomorrow)}",
    "acha que nevara depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "acha que nevara hoje": "execute_action{weather(forecast_today)}",
    "acha que qual a temperatura amanha": "execute_action{weather(temperature_tomorrow)}",
    "acha que qual a temperatura depois de amanha": "execute_action{weather(temperature_aftertm)}",
    "acha que qual a temperatura hoje": "execute_action{weather(temperature_today)}",
    "acha que qual a temperatura": "execute_action{weather(temperature_today)}",
    "acha que qual sera a temperatura amanha": "execute_action{weather(temperature_tomorrow)}",
    "acha que qual sera a temperatura depois de amanha": "execute_action{weather(temperature_aftertm)}",
    "acha que sera que chovera amanha": "execute_action{weather(forecast_tomorrow)}",
    "acha que sera que chovera depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "acha que sera que chovera hoje": "execute_action{weather(forecast_today)}",
    "acha que sera que fara sol amanha": "execute_action{weather(forecast_tomorrow)}",
    "acha que sera que fara sol depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "acha que sera que fara sol hoje": "execute_action{weather(forecast_today)}",
    "acha que sera que nevara amanha": "execute_action{weather(forecast_tomorrow)}",
    "acha que sera que nevara depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "acha que sera que nevara hoje": "execute_action{weather(forecast_today)}",
    "acha que sera que vai chover amanha": "execute_action{weather(forecast_tomorrow)}",
    "acha que sera que vai chover depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "acha que sera que vai chover hoje": "execute_action{weather(forecast_today)}",
    "acha que sera que vai fazer sol amanha": "execute_action{weather(forecast_tomorrow)}",
    "acha que sera que vai fazer sol depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "acha que sera que vai fazer sol hoje": "execute_action{weather(forecast_today)}",
    "acha que sera que vai nevar amanha": "execute_action{weather(forecast_tomorrow)}",
    "acha que sera que vai nevar depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "acha que sera que vai nevar hoje": "execute_action{weather(forecast_today)}",
    "acha que vai chover amanha": "execute_action{weather(forecast_tomorrow)}",
    "acha que vai chover depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "acha que vai chover hoje": "execute_action{weather(forecast_today)}",
    "acha que vai fazer sol amanha": "execute_action{weather(forecast_tomorrow)}",
    "acha que vai fazer sol depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "acha que vai fazer sol hoje": "execute_action{weather(forecast_today)}",
    "acha que vai nevar amanha": "execute_action{weather(forecast_tomorrow)}",
    "acha que vai nevar depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "acha que vai nevar hoje": "execute_action{weather(forecast_today)}",
    "amanha vai ser frio": "execute_action{weather(temperature_tomorrow)}",
    "amanha vai ser quente": "execute_action{weather(temperature_tomorrow)}",
    "ande para a frente": "infelizmente ainda não consigo andar",
    "ande para o lado direito": "infelizmente ainda não consigo andar",
    "ande para o lado esquerdo": "infelizmente ainda não consigo andar",
    "ande para tras": "infelizmente ainda não consigo andar",
    "bota pra ouvir": "execute_action{music()}",
    "bota pra ouvir a cancao": "execute_action{music()}",
    "bota pra ouvir a musica": "execute_action{music()}",
    "bota pra ouvir o som": "execute_action{music()}",
    "bota pra reproduzir": "execute_action{music()}",
    "bota pra reproduzir a cancao": "execute_action{music()}",
    "bota pra reproduzir a musica": "execute_action{music()}",
    "bota pra reproduzir o som": "execute_action{music()}",
    "bota pra tocar": "execute_action{music()}",
    "bota pra tocar a cancao": "execute_action{music()}",
    "bota pra tocar a musica": "execute_action{music()}",
    "bota pra tocar o som": "execute_action{music()}",
    "bota um som": "execute_action{music()}",
    "byte amanha vai ser frio": "execute_action{weather(temperature_tomorrow)}",
    "byte amanha vai ser quente": "execute_action{weather(temperature_tomorrow)}",
    "byte como esta o clima hoje": "execute_action{weather(forecast_today)}",
    "byte como esta o tempo hoje": "execute_action{weather(forecast_today)}",
    "byte como estara o clima amanha": "execute_action{weather(forecast_tomorrow)}",
    "byte como estara o clima depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "byte como estara o clima hoje": "execute_action{weather(forecast_today)}",
    "byte como estara o tempo amanha": "execute_action{weather(forecast_tomorrow)}",
    "byte como estara o tempo depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "byte como estara o tempo hoje": "execute_action{weather(forecast_today)}",
    "byte depois de amanha vai ser frio": "execute_action{weather(temperature_aftertm)}",
    "byte depois de amanha vai ser quente": "execute_action{weather(temperature_aftertm)}",
    "byte esta calor hoje": "execute_action{weather(temperature_today)}",
    "byte esta feliz": "estou feliz execute_action{emotion(happy)}",
    "byte esta frio hoje": "execute_action{weather(temperature_today)}",
    "byte esta quente hoje": "execute_action{weather(forecast_today)}",
    "byte esta seco hoje": "execute_action{weather(forecast_today)}",
    "byte esta umido hoje": "execute_action{weather(forecast_today)}",
    "byte estara calor amanha": "execute_action{weather(forecast_tomorrow)}",
    "byte estara calor depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "byte estara calor hoje": "execute_action{weather(temperature_today)}",
    "byte estara frio amanha": "execute_action{weather(forecast_tomorrow)}",
    "byte estara frio depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "byte estara frio hoje": "execute_action{weather(temperature_today)}",
    "byte estara quente amanha": "execute_action{weather(forecast_tomorrow)}",
    "byte estara quente depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "byte estara seco amanha": "execute_action{weather(forecast_tomorrow)}",
    "byte estara seco depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "byte estara umido amanha": "execute_action{weather(forecast_tomorrow)}",
    "byte estara umido depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "byte fara calor amanha": "execute_action{weather(temperature_tomorrow)}",
    "byte fara calor depois de amanha": "execute_action{weather(temperature_aftertm)}",
    "byte fara calor hoje": "execute_action{weather(temperature_today)}",
    "byte fara frio amanha": "execute_action{weather(temperature_tomorrow)}",
    "byte fara frio depois de amanha": "execute_action{weather(temperature_aftertm)}",
    "byte fara frio hoje": "execute_action{weather(temperature_today)}",
    "byte fica feliz": "estou feliz execute_action{emotion(happy)}",
    "byte fique feliz": "estou feliz execute_action{emotion(happy)}",
    "byte hoje vai ser frio": "execute_action{weather(temperature_today)}",
    "byte hoje vai ser quente": "execute_action{weather(temperature_today)}",
    "byte ta feliz": "estou feliz execute_action{emotion(happy)}",
    "byte vai fazer calor amanha": "execute_action{weather(temperature_tomorrow)}",
    "byte vai fazer calor depois de amanha": "execute_action{weather(temperature_aftertm)}",
    "byte vai fazer calor hoje": "execute_action{weather(temperature_today)}",
    "byte vai fazer frio amanha": "execute_action{weather(temperature_tomorrow)}",
    "byte vai fazer frio depois de amanha": "execute_action{weather(temperature_aftertm)}",
    "byte vai fazer frio hoje": "execute_action{weather(temperature_today)}",
    "byte vai ficar calor amanha": "execute_action{weather(temperature_tomorrow)}",
    "byte vai ficar calor depois de amanha": "execute_action{weather(temperature_aftertm)}",
    "byte vai ficar calor hoje": "execute_action{weather(temperature_today)}",
    "byte vai ficar frio amanha": "execute_action{weather(temperature_tomorrow)}",
    "byte vai ficar frio depois de amanha": "execute_action{weather(temperature_aftertm)}",
    "byte vai ficar frio hoje": "execute_action{weather(temperature_today)}",
    "chove amanha": "execute_action{weather(forecast_tomorrow)}",
    "chove depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "chove hoje": "execute_action{weather(forecast_today)}",
    "chovera amanha": "execute_action{weather(forecast_tomorrow)}",
    "chovera depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "chovera hoje": "execute_action{weather(forecast_today)}",
    "coloca o som": "execute_action{music()}",
    "coloca pra ouvir": "execute_action{music()}",
    "coloca pra ouvir a cancao": "execute_action{music()}",
    "coloca pra ouvir a musica": "execute_action{music()}",
    "coloca pra ouvir o som": "execute_action{music()}",
    "coloca pra reproduzir": "execute_action{music()}",
    "coloca pra reproduzir a cancao": "execute_action{music()}",
    "coloca pra reproduzir a musica": "execute_action{music()}",
    "coloca pra reproduzir o som": "execute_action{music()}",
    "coloca pra tocar": "execute_action{music()}",
    "coloca pra tocar a cancao": "execute_action{music()}",
    "coloca pra tocar a musica": "execute_action{music()}",
    "coloca pra tocar o som": "execute_action{music()}",
    "coloca um som": "execute_action{music()}",
    "como esta o clima hoje": "execute_action{weather(forecast_today)}",
    "como esta o tempo hoje": "execute_action{weather(forecast_today)}",
    "como estara o clima amanha": "execute_action{weather(forecast_tomorrow)}",
    "como estara o clima depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "como estara o clima hoje": "execute_action{weather(forecast_today)}",
    "como estara o tempo amanha": "execute_action{weather(forecast_tomorrow)}",
    "como estara o tempo depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "como estara o tempo hoje": "execute_action{weather(forecast_today)}",
    "como foi": "execute_action{search()}",
    "como foi q": "execute_action{search()}",
    "como foi que": "execute_action{search()}",
    "conta uma coisa engracada": "execute_action{joke(random)}",
    "conta uma piada": "execute_action{joke(random)}",
    "conta uma piada astronomica": "execute_action{joke(astronomia)}",
    "conta uma piada biologia": "execute_action{joke(biologia)}",
    "conta uma piada de algebra": "execute_action{joke(matematica)}",
    "conta uma piada de alimentos": "execute_action{joke(comida)}",
    "conta uma piada de animais": "execute_action{joke(animais)}",
    "conta uma piada de astronomia": "execute_action{joke(astronomia)}",
    "conta uma piada de automoveis": "execute_action{joke(carros)}",
    "conta uma piada de biologia": "execute_action{joke(biologia)}",
    "conta uma piada de carros": "execute_action{joke(carros)}",
    "conta uma piada de cinema": "execute_action{joke(filmes)}",
    "conta uma piada de comida": "execute_action{joke(comida)}",
    "conta uma piada de computacao": "execute_action{joke(informatica)}",
    "conta uma piada de computadores": "execute_action{joke(informatica)}",
    "conta uma piada de cumulo": "execute_action{joke(cumulo)}",
    "conta uma piada de espaco": "execute_action{joke(astronomia)}",
    "conta uma piada de farmacia": "execute_action{joke(remedio)}",
    "conta uma piada de filmes": "execute_action{joke(filmes)}",
    "conta uma piada de filosofia": "execute_action{joke(filosofia)}",
    "conta uma piada de filosofos": "execute_action{joke(filosofia)}",
    "conta uma piada de fisica": "execute_action{joke(fisica)}",
    "conta uma piada de games": "execute_action{joke(games)}",
    "conta uma piada de geografia": "execute_action{joke(geografia)}",
    "conta uma piada de historia": "execute_action{joke(historia)}",
    "conta uma piada de informatica": "execute_action{joke(informatica)}",
    "conta uma piada de jogos": "execute_action{joke(games)}",
    "conta uma piada de lingua portuguesa": "execute_action{joke(portugues)}",
    "conta uma piada de matematica": "execute_action{joke(matematica)}",
    "conta uma piada de medicina": "execute_action{joke(biologia)}",
    "conta uma piada de musica": "execute_action{joke(musica)}",
    "conta uma piada de musical": "execute_action{joke(musica)}",
    "conta uma piada de plantas": "execute_action{joke(plantas)}",
    "conta uma piada de pontinho": "execute_action{joke(pontinho)}",
    "conta uma piada de portugues": "execute_action{joke(portugues)}",
    "conta uma piada de quimica": "execute_action{joke(quimica)}",
    "conta uma piada de remedio": "execute_action{joke(remedio)}",
    "conta uma piada de veiculos": "execute_action{joke(carros)}",
    "conta uma piada geografica": "execute_action{joke(geografia)}",
    "conta uma piada historica": "execute_action{joke(historia)}",
    "conte uma coisa engracada": "execute_action{joke(random)}",
    "conte uma piada": "execute_action{joke(random)}",
    "conte uma piada astronomica": "execute_action{joke(astronomia)}",
    "conte uma piada biologica": "execute_action{joke(biologia)}",
    "conte uma piada de algebra": "execute_action{joke(matematica)}",
    "conte uma piada de alimentos": "execute_action{joke(comida)}",
    "conte uma piada de animais": "execute_action{joke(animais)}",
    "conte uma piada de astronomia": "execute_action{joke(astronomia)}",
    "conte uma piada de automoveis": "execute_action{joke(carros)}",
    "conte uma piada de biologia": "execute_action{joke(biologia)}",
    "conte uma piada de carros": "execute_action{joke(carros)}",
    "conte uma piada de cinema": "execute_action{joke(filmes)}",
    "conte uma piada de comida": "execute_action{joke(comida)}",
    "conte uma piada de computacao": "execute_action{joke(informatica)}",
    "conte uma piada de computadores": "execute_action{joke(informatica)}",
    "conte uma piada de cumulo": "execute_action{joke(cumulo)}",
    "conte uma piada de espaco": "execute_action{joke(astronomia)}",
    "conte uma piada de farmacia": "execute_action{joke(remedio)}",
    "conte uma piada de filmes": "execute_action{joke(filmes)}",
    "conte uma piada de filosofia": "execute_action{joke(filosofia)}",
    "conte uma piada de filosofos": "execute_action{joke(filosofia)}",
    "conte uma piada de fisica": "execute_action{joke(fisica)}",
    "conte uma piada de games": "execute_action{joke(games)}",
    "conte uma piada de geografia": "execute_action{joke(geografia)}",
    "conte uma piada de historia": "execute_action{joke(historia)}",
    "conte uma piada de informatica": "execute_action{joke(informatica)}",
    "conte uma piada de jogos": "execute_action{joke(games)}",
    "conte uma piada de lingua portuguesa": "execute_action{joke(portugues)}",
    "conte uma piada de matematica": "execute_action{joke(matematica)}",
    "conte uma piada de medicina": "execute_action{joke(biologia)}",
    "conte uma piada de musica": "execute_action{joke(musica)}",
    "conte uma piada de musical": "execute_action{joke(musica)}",
    "conte uma piada de plantas": "execute_action{joke(plantas)}",
    "conte uma piada de pontinho": "execute_action{joke(pontinho)}",
    "conte uma piada de portugues": "execute_action{joke(portugues)}",
    "conte uma piada de quimica": "execute_action{joke(quimica)}",
    "conte uma piada de remedio": "execute_action{joke(remedio)}",
    "conte uma piada de veiculos": "execute_action{joke(carros)}",
    "conte uma piada geografica": "execute_action{joke(geografia)}",
    "conte uma piada historica": "execute_action{joke(historia)}",
    "depois de amanha vai ser frio": "execute_action{weather(temperature_aftertm)}",
    "depois de amanha vai ser quente": "execute_action{weather(temperature_aftertm)}",
    "em qual ano estamos": "execute_action{get_time(year)}",
    "em que ano estamos": "execute_action{get_time(year)}",
    "em que dia estamos": "execute_action{get_time(hour)}",
    "esta calor hoje": "execute_action{weather(temperature_today)}",
    "esta chovendo agora": "execute_action{weather(forecast_today)}",
    "esta feliz": "estou feliz execute_action{emotion(happy)}",
    "esta frio hoje": "execute_action{weather(temperature_today)}",
    "esta normal": "estou normal execute_action{emotion(neutral)}",
    "esta quente hoje": "execute_action{weather(forecast_today)}",
    "esta seco hoje": "execute_action{weather(forecast_today)}",
    "esta umido hoje": "execute_action{weather(forecast_today)}",
    "estara calor amanha": "execute_action{weather(forecast_tomorrow)}",
    "estara calor depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "estara calor hoje": "execute_action{weather(temperature_today)}",
    "estara frio amanha": "execute_action{weather(forecast_tomorrow)}",
    "estara frio depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "estara frio hoje": "execute_action{weather(temperature_today)}",
    "estara quente amanha": "execute_action{weather(forecast_tomorrow)}",
    "estara quente depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "estara seco amanha": "execute_action{weather(forecast_tomorrow)}",
    "estara seco depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "estara umido amanha": "execute_action{weather(forecast_tomorrow)}",
    "estara umido depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "esteja feliz": "estou feliz execute_action{emotion(happy)}",
    "esteja normal": "estou normal execute_action{emotion(neutral)}",
    "esteja triste": "por que tenho que ficar triste? execute_action{emotion(sad)}",
    "esteje feliz": "estou feliz execute_action{emotion(happy)}",
    "esteje normal": "estou normal execute_action{emotion(neutral)}",
    "esteje triste": "por que tenho que ficar triste? execute_action{emotion(sad)}",
    "fala uma coisa engracada": "execute_action{joke(random)}",
    "fala uma piada": "execute_action{joke(random)}",
    "fala uma piada biologia": "execute_action{joke(biologia)}",
    "fale uma coisa engracada": "execute_action{joke(random)}",
    "fale uma piada": "execute_action{joke(random)}",
    "fara calor amanha": "execute_action{weather(temperature_tomorrow)}",
    "fara calor depois de amanha": "execute_action{weather(temperature_aftertm)}",
    "fara calor hoje": "execute_action{weather(temperature_today)}",
    "fara frio amanha": "execute_action{weather(temperature_tomorrow)}",
    "fara frio depois de amanha": "execute_action{weather(temperature_aftertm)}",
    "fara frio hoje": "execute_action{weather(temperature_today)}",
    "fara quente amanha": "execute_action{weather(temperature_tomorrow)}",
    "fara quente depois de amanha": "execute_action{weather(temperature_aftertm)}",
    "fara quente hoje": "execute_action{weather(temperature_today)}",
    "fara sol amanha": "execute_action{weather(forecast_tomorrow)}",
    "fara sol depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "fara sol hoje": "execute_action{weather(forecast_today)}",
    "faz calor amanha": "execute_action{weather(temperature_tomorrow)}",
    "faz calor depois de amanha": "execute_action{weather(temperature_aftertm)}",
    "faz calor hoje": "execute_action{weather(temperature_today)}",
    "faz frio amanha": "execute_action{weather(temperature_tomorrow)}",
    "faz frio depois de amanha": "execute_action{weather(temperature_aftertm)}",
    "faz frio hoje": "execute_action{weather(temperature_today)}",
    "faz quente amanha": "execute_action{weather(temperature_tomorrow)}",
    "faz quente depois de amanha": "execute_action{weather(temperature_aftertm)}",
    "faz quente hoje": "execute_action{weather(temperature_today)}",
    "fica feliz": "estou feliz execute_action{emotion(happy)}",
    "fica normal": "estou normal execute_action{emotion(neutral)}",
    "fica triste": "por que tenho que ficar triste? execute_action{emotion(sad)}",
    "fique feliz": "estou feliz execute_action{emotion(happy)}",
    "fique normal": "estou normal execute_action{emotion(neutral)}",
    "fique triste": "por que tenho que ficar triste? execute_action{emotion(sad)}",
    "hoje vai ser frio": "execute_action{weather(temperature_today)}",
    "hoje vai ser quente": "execute_action{weather(temperature_today)}",
    "me conta uma piada": "execute_action{joke(random)}",
    "me conta uma piada biologica": "execute_action{joke(biologia)}",
    "me conta uma piada sobre algebra": "execute_action{joke(matematica)}",
    "me conta uma piada sobre alimentos": "execute_action{joke(comida)}",
    "me conta uma piada sobre animais": "execute_action{joke(animais)}",
    "me conta uma piada sobre astronomia": "execute_action{joke(astronomia)}",
    "me conta uma piada sobre automoveis": "execute_action{joke(carros)}",
    "me conta uma piada sobre biologia": "execute_action{joke(biologia)}",
    "me conta uma piada sobre carros": "execute_action{joke(carros)}",
    "me conta uma piada sobre cinema": "execute_action{joke(filmes)}",
    "me conta uma piada sobre comida": "execute_action{joke(comida)}",
    "me conta uma piada sobre computacao": "execute_action{joke(informatica)}",
    "me conta uma piada sobre computadores": "execute_action{joke(informatica)}",
    "me conta uma piada sobre cumulo": "execute_action{joke(cumulo)}",
    "me conta uma piada sobre espaco": "execute_action{joke(astronomia)}",
    "me conta uma piada sobre farmacia": "execute_action{joke(remedio)}",
    "me conta uma piada sobre filmes": "execute_action{joke(filmes)}",
    "me conta uma piada sobre filosofia": "execute_action{joke(filosofia)}",
    "me conta uma piada sobre filosofos": "execute_action{joke(filosofia)}",
    "me conta uma piada sobre fisica": "execute_action{joke(fisica)}",
    "me conta uma piada sobre games": "execute_action{joke(games)}",
    "me conta uma piada sobre geografia": "execute_action{joke(geografia)}",
    "me conta uma piada sobre historia": "execute_action{joke(historia)}",
    "me conta uma piada sobre informatica": "execute_action{joke(informatica)}",
    "me conta uma piada sobre jogos": "execute_action{joke(games)}",
    "me conta uma piada sobre lingua portuguesa": "execute_action{joke(portugues)}",
    "me conta uma piada sobre matematica": "execute_action{joke(matematica)}",
    "me conta uma piada sobre medicina": "execute_action{joke(biologia)}",
    "me conta uma piada sobre musica": "execute_action{joke(musica)}",
    "me conta uma piada sobre plantas": "execute_action{joke(plantas)}",
    "me conta uma piada sobre pontinhos": "execute_action{joke(pontinho)}",
    "me conta uma piada sobre portugues": "execute_action{joke(portugues)}",
    "me conta uma piada sobre quimica": "execute_action{joke(quimica)}",
    "me conta uma piada sobre remedios": "execute_action{joke(remedio)}",
    "me conta uma piada sobre veiculos": "execute_action{joke(carros)}",
    "me conte piada algebra": "execute_action{joke(matematica)}",
    "me conte piada alimentos": "execute_action{joke(comida)}",
    "me conte piada animais": "execute_action{joke(animais)}",
    "me conte piada astronomia": "execute_action{joke(astronomia)}",
    "me conte piada automoveis": "execute_action{joke(carros)}",
    "me conte piada biologia": "execute_action{joke(biologia)}",
    "me conte piada carros": "execute_action{joke(carros)}",
    "me conte piada cinema": "execute_action{joke(filmes)}",
    "me conte piada comida": "execute_action{joke(comida)}",
    "me conte piada computacao": "execute_action{joke(informatica)}",
    "me conte piada computadores": "execute_action{joke(informatica)}",
    "me conte piada cumulo": "execute_action{joke(cumulo)}",
    "me conte piada espaco": "execute_action{joke(astronomia)}",
    "me conte piada farmacia": "execute_action{joke(remedio)}",
    "me conte piada filmes": "execute_action{joke(filmes)}",
    "me conte piada filosofia": "execute_action{joke(filosofia)}",
    "me conte piada filosofos": "execute_action{joke(filosofia)}",
    "me conte piada fisica": "execute_action{joke(fisica)}",
    "me conte piada games": "execute_action{joke(games)}",
    "me conte piada geografia": "execute_action{joke(geografia)}",
    "me conte piada historia": "execute_action{joke(historia)}",
    "me conte piada informatica": "execute_action{joke(informatica)}",
    "me conte piada jogos": "execute_action{joke(games)}",
    "me conte piada lingua portuguesa": "execute_action{joke(portugues)}",
    "me conte piada matematica": "execute_action{joke(matematica)}",
    "me conte piada medicina": "execute_action{joke(biologia)}",
    "me conte piada musica": "execute_action{joke(musica)}",
    "me conte piada plantas": "execute_action{joke(plantas)}",
    "me conte piada pontinhos": "execute_action{joke(pontinho)}",
    "me conte piada portugues": "execute_action{joke(portugues)}",
    "me conte piada quimica": "execute_action{joke(quimica)}",
    "me conte piada remedios": "execute_action{joke(remedio)}",
    "me conte piada veiculos": "execute_action{joke(carros)}",
    "me conte uma piada": "execute_action{joke(random)}",
    "me conte uma piada biologica": "execute_action{joke(biologia)}",
    "me conte uma piada de algebra": "execute_action{joke(matematica)}",
    "me conte uma piada de alimentos": "execute_action{joke(comida)}",
    "me conte uma piada de animais": "execute_action{joke(animais)}",
    "me conte uma piada de astronomia": "execute_action{joke(astronomia)}",
    "me conte uma piada de automoveis": "execute_action{joke(carros)}",
    "me conte uma piada de biologia": "execute_action{joke(biologia)}",
    "me conte uma piada de carros": "execute_action{joke(carros)}",
    "me conte uma piada de cinema": "execute_action{joke(filmes)}",
    "me conte uma piada de comida": "execute_action{joke(comida)}",
    "me conte uma piada de computacao": "execute_action{joke(informatica)}",
    "me conte uma piada de computadores": "execute_action{joke(informatica)}",
    "me conte uma piada de cumulo": "execute_action{joke(cumulo)}",
    "me conte uma piada de espaco": "execute_action{joke(astronomia)}",
    "me conte uma piada de farmacia": "execute_action{joke(remedio)}",
    "me conte uma piada de filmes": "execute_action{joke(filmes)}",
    "me conte uma piada de filosofia": "execute_action{joke(filosofia)}",
    "me conte uma piada de filosofos": "execute_action{joke(filosofia)}",
    "me conte uma piada de fisica": "execute_action{joke(fisica)}",
    "me conte uma piada de games": "execute_action{joke(games)}",
    "me conte uma piada de geografia": "execute_action{joke(geografia)}",
    "me conte uma piada de historia": "execute_action{joke(historia)}",
    "me conte uma piada de informatica": "execute_action{joke(informatica)}",
    "me conte uma piada de jogos": "execute_action{joke(games)}",
    "me conte uma piada de lingua portuguesa": "execute_action{joke(portugues)}",
    "me conte uma piada de matematica": "execute_action{joke(matematica)}",
    "me conte uma piada de medicina": "execute_action{joke(biologia)}",
    "me conte uma piada de musica": "execute_action{joke(musica)}",
    "me conte uma piada de plantas": "execute_action{joke(plantas)}",
    "me conte uma piada de pontinhos": "execute_action{joke(pontinho)}",
    "me conte uma piada de portugues": "execute_action{joke(portugues)}",
    "me conte uma piada de quimica": "execute_action{joke(quimica)}",
    "me conte uma piada de remedios": "execute_action{joke(remedio)}",
    "me conte uma piada de veiculos": "execute_action{joke(carros)}",
    "me conte uma piada sobre algebra": "execute_action{joke(matematica)}",
    "me conte uma piada sobre alimentos": "execute_action{joke(comida)}",
    "me conte uma piada sobre animais": "execute_action{joke(animais)}",
    "me conte uma piada sobre astronomia": "execute_action{joke(astronomia)}",
    "me conte uma piada sobre automoveis": "execute_action{joke(carros)}",
    "me conte uma piada sobre biologia": "execute_action{joke(biologia)}",
    "me conte uma piada sobre carros": "execute_action{joke(carros)}",
    "me conte uma piada sobre cinema": "execute_action{joke(filmes)}",
    "me conte uma piada sobre comida": "execute_action{joke(comida)}",
    "me conte uma piada sobre computacao": "execute_action{joke(informatica)}",
    "me conte uma piada sobre computadores": "execute_action{joke(informatica)}",
    "me conte uma piada sobre cumulo": "execute_action{joke(cumulo)}",
    "me conte uma piada sobre espaco": "execute_action{joke(astronomia)}",
    "me conte uma piada sobre farmacia": "execute_action{joke(remedio)}",
    "me conte uma piada sobre filmes": "execute_action{joke(filmes)}",
    "me conte uma piada sobre filosofia": "execute_action{joke(filosofia)}",
    "me conte uma piada sobre filosofos": "execute_action{joke(filosofia)}",
    "me conte uma piada sobre fisica": "execute_action{joke(fisica)}",
    "me conte uma piada sobre games": "execute_action{joke(games)}",
    "me conte uma piada sobre geografia": "execute_action{joke(geografia)}",
    "me conte uma piada sobre historia": "execute_action{joke(historia)}",
    "me conte uma piada sobre informatica": "execute_action{joke(informatica)}",
    "me conte uma piada sobre jogos": "execute_action{joke(games)}",
    "me conte uma piada sobre lingua portuguesa": "execute_action{joke(portugues)}",
    "me conte uma piada sobre matematica": "execute_action{joke(matematica)}",
    "me conte uma piada sobre medicina": "execute_action{joke(biologia)}",
    "me conte uma piada sobre musica": "execute_action{joke(musica)}",
    "me conte uma piada sobre plantas": "execute_action{joke(plantas)}",
    "me conte uma piada sobre pontinhos": "execute_action{joke(pontinho)}",
    "me conte uma piada sobre portugues": "execute_action{joke(portugues)}",
    "me conte uma piada sobre quimica": "execute_action{joke(quimica)}",
    "me conte uma piada sobre remedios": "execute_action{joke(remedio)}",
    "me conte uma piada sobre veiculos": "execute_action{joke(carros)}",
    "nevara amanha": "execute_action{weather(forecast_tomorrow)}",
    "nevara depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "nevara hoje": "execute_action{weather(forecast_today)}",
    "pesquise": "execute_action{search()}",
    "pesquise se": "execute_action{search()}",
    "piada alimento": "execute_action{joke(comida)}",
    "piada animais": "execute_action{joke(animais)}",
    "piada astronomia": "execute_action{joke(astronomia)}",
    "piada biologia": "execute_action{joke(biologia)}",
    "piada carros": "execute_action{joke(carros)}",
    "piada comida": "execute_action{joke(comida)}",
    "piada cumulo": "execute_action{joke(cumulo)}",
    "piada farmacia": "execute_action{joke(remedio)}",
    "piada filmes": "execute_action{joke(filmes)}",
    "piada filosofia": "execute_action{joke(filosofia)}",
    "piada fisica": "execute_action{joke(fisica)}",
    "piada games": "execute_action{joke(games)}",
    "piada geografia": "execute_action{joke(geografia)}",
    "piada historia": "execute_action{joke(historia)}",
    "piada informatica": "execute_action{joke(informatica)}",
    "piada jogos": "execute_action{joke(games)}",
    "piada matematica": "execute_action{joke(matematica)}",
    "piada musica": "execute_action{joke(musica)}",
    "piada plantas": "execute_action{joke(plantas)}",
    "piada pontinho": "execute_action{joke(pontinho)}",
    "piada portugues": "execute_action{joke(portugues)}",
    "piada quimica": "execute_action{joke(quimica)}",
    "piada remedio": "execute_action{joke(remedio)}",
    "piada veiculos": "execute_action{joke(carros)}",
    "piadas alimento": "execute_action{joke(comida)}",
    "piadas animais": "execute_action{joke(animais)}",
    "piadas astronomia": "execute_action{joke(astronomia)}",
    "piadas biologia": "execute_action{joke(biologia)}",
    "piadas carros": "execute_action{joke(carros)}",
    "piadas comida": "execute_action{joke(comida)}",
    "piadas cumulo": "execute_action{joke(cumulo)}",
    "piadas farmacia": "execute_action{joke(remedio)}",
    "piadas filmes": "execute_action{joke(filmes)}",
    "piadas filosofia": "execute_action{joke(filosofia)}",
    "piadas fisica": "execute_action{joke(fisica)}",
    "piadas games": "execute_action{joke(games)}",
    "piadas geografia": "execute_action{joke(geografia)}",
    "piadas historia": "execute_action{joke(historia)}",
    "piadas informatica": "execute_action{joke(informatica)}",
    "piadas jogos": "execute_action{joke(games)}",
    "piadas matematica": "execute_action{joke(matematica)}",
    "piadas musica": "execute_action{joke(musica)}",
    "piadas plantas": "execute_action{joke(plantas)}",
    "piadas pontinho": "execute_action{joke(pontinho)}",
    "piadas portugues": "execute_action{joke(portugues)}",
    "piadas quimica": "execute_action{joke(quimica)}",
    "piadas remedio": "execute_action{joke(remedio)}",
    "piadas veiculos": "execute_action{joke(carros)}",
    "qual a temperatura agora": "execute_action{weather(temperature_today)}",
    "qual a temperatura amanha": "execute_action{weather(temperature_tomorrow)}",
    "qual a temperatura depois de amanha": "execute_action{weather(temperature_aftertm)}",
    "qual a temperatura hoje": "execute_action{weather(temperature_today)}",
    "qual a temperatura": "execute_action{weather(temperature_today)}",
    "qual ano estamos": "execute_action{get_time(year)}",
    "qual e a temperatura agora": "execute_action{weather(temperature_today)}",
    "qual e meu nome": "execute_action{recognition()}",
    "qual e o nome do ser no qual esta falando contigo": "execute_action{recognition()}",
    "qual sera a temperatura agora": "execute_action{weather(temperature_today)}",
    "qual sera a temperatura amanha": "execute_action{weather(temperature_tomorrow)}",
    "qual sera a temperatura depois de amanha": "execute_action{weather(temperature_aftertm)}",
    "quando e": "execute_action{search()}",
    "quando e a data": "execute_action{search()}",
    "quando e a data que": "execute_action{search()}",
    "quando e que": "execute_action{search()}",
    "quando foi": "execute_action{search()}",
    "quando foi a data": "execute_action{search()}",
    "quando foi a data que": "execute_action{search()}",
    "quando foi que": "execute_action{search()}",
    "quando foi que o": "execute_action{search()}",
    "quando q": "execute_action{search()}",
    "quando que": "execute_action{search()}",
    "que ano a gente esta": "execute_action{get_time(year)}",
    "que ano e esse": "execute_action{get_time(year)}",
    "que ano e hoje": "execute_action{get_time(year)}",
    "que ano estamos": "execute_action{get_time(year)}",
    "que ano estamos": "execute_action{get_time(year)}",
    "que ano que e isso": "execute_action{get_time(year)}",
    "que anos e": "execute_action{get_time(year)}",
    "que anos sao": "execute_action{get_time(year)}",
    "que dia da semana a gente esta": "execute_action{get_time(weekday)}",
    "que dia da semana a gente ta": "execute_action{get_time(weekday)}",
    "que dia da semana e hoje": "execute_action{get_time(weekday)}",
    "que dia da semana estamos": "execute_action{get_time(weekday)}",
    "que dia da semana que e isso": "execute_action{get_time(weekday)}",
    "que dia e hj": "execute_action{get_time(date)}",
    "que dia e hoje": "execute_action{get_time(date)}",
    "que dia e": "execute_action{get_time(date)}",
    "que dia estamos": "execute_action{get_time(date)}",
    "que dia que e isso": "execute_action{get_time(date)}",
    "que dias da semana e": "execute_action{get_time(weekday)}",
    "que dias da semana sao": "execute_action{get_time(weekday)}",
    "que dias e": "execute_action{get_time(date)}",
    "que dias sao": "execute_action{get_time(date)}",
    "que horas e agora": "execute_action{get_time(hour)}",
    "que horas e": "execute_action{get_time(hour)}",
    "que horas que e isso": "execute_action{get_time(hour)}",
    "que horas que sao": "execute_action{get_time(hour)}",
    "que horas sao": "execute_action{get_time(hour)}",
    "quem e": "execute_action{search()}",
    "quem e o ser no qual esta falando contigo": "execute_action{recognition()}",
    "quem e o ser que esta falando contigo": "execute_action{recognition()}",
    "quem e que": "execute_action{search()}",
    "quem esta falando contigo": "execute_action{recognition()}",
    "quem foi": "execute_action{search()}",
    "quem foi o": "execute_action{search()}",
    "quem foi que": "execute_action{search()}",
    "quem que sou eu": "execute_action{recognition()}",
    "quem sou eu": "execute_action{recognition()}",
    "quero o um som": "execute_action{music()}",
    "quero ouvir": "execute_action{music()}",
    "quero ouvir a cancao": "execute_action{music()}",
    "quero ouvir a musica": "execute_action{music()}",
    "quero ouvir um som": "execute_action{music()}",
    "quero ouvir uma cancao": "execute_action{music()}",
    "quero ouvir uma musica": "execute_action{music()}",
    "quero ouvir uma piada": "execute_action{joke(random)}",
    "reproduza": "execute_action{music()}",
    "reproduzir a musica": "execute_action{music()}",
    "reproduzir uma musica": "execute_action{music()}",
    "robo amanha vai ser frio": "execute_action{weather(temperature_tomorrow)}",
    "robo amanha vai ser quente": "execute_action{weather(temperature_tomorrow)}",
    "robo como esta o clima hoje": "execute_action{weather(forecast_today)}",
    "robo como esta o tempo hoje": "execute_action{weather(forecast_today)}",
    "robo como estara o clima amanha": "execute_action{weather(forecast_tomorrow)}",
    "robo como estara o clima depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "robo como estara o clima hoje": "execute_action{weather(forecast_today)}",
    "robo como estara o tempo amanha": "execute_action{weather(forecast_tomorrow)}",
    "robo como estara o tempo depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "robo como estara o tempo hoje": "execute_action{weather(forecast_today)}",
    "robo depois de amanha vai ser frio": "execute_action{weather(temperature_aftertm)}",
    "robo depois de amanha vai ser quente": "execute_action{weather(temperature_aftertm)}",
    "robo esta calor hoje": "execute_action{weather(temperature_today)}",
    "robo esta feliz": "estou feliz execute_action{emotion(happy)}",
    "robo esta frio hoje": "execute_action{weather(temperature_today)}",
    "robo esta quente hoje": "execute_action{weather(forecast_today)}",
    "robo esta seco hoje": "execute_action{weather(forecast_today)}",
    "robo esta umido hoje": "execute_action{weather(forecast_today)}",
    "robo estara calor amanha": "execute_action{weather(forecast_tomorrow)}",
    "robo estara calor depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "robo estara calor hoje": "execute_action{weather(temperature_today)}",
    "robo estara frio amanha": "execute_action{weather(forecast_tomorrow)}",
    "robo estara frio depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "robo estara frio hoje": "execute_action{weather(temperature_today)}",
    "robo estara quente amanha": "execute_action{weather(forecast_tomorrow)}",
    "robo estara quente depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "robo estara seco amanha": "execute_action{weather(forecast_tomorrow)}",
    "robo estara seco depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "robo estara umido amanha": "execute_action{weather(forecast_tomorrow)}",
    "robo estara umido depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "robo fara calor amanha": "execute_action{weather(temperature_tomorrow)}",
    "robo fara calor depois de amanha": "execute_action{weather(temperature_aftertm)}",
    "robo fara calor hoje": "execute_action{weather(temperature_today)}",
    "robo fara frio amanha": "execute_action{weather(temperature_tomorrow)}",
    "robo fara frio depois de amanha": "execute_action{weather(temperature_aftertm)}",
    "robo fara frio hoje": "execute_action{weather(temperature_today)}",
    "robo fica feliz": "estou feliz execute_action{emotion(happy)}",
    "robo fique feliz": "estou feliz execute_action{emotion(happy)}",
    "robo hoje vai ser frio": "execute_action{weather(temperature_today)}",
    "robo hoje vai ser quente": "execute_action{weather(temperature_today)}",
    "robo ta feliz": "estou feliz execute_action{emotion(happy)}",
    "robo vai fazer calor amanha": "execute_action{weather(temperature_tomorrow)}",
    "robo vai fazer calor depois de amanha": "execute_action{weather(temperature_aftertm)}",
    "robo vai fazer calor hoje": "execute_action{weather(temperature_today)}",
    "robo vai fazer frio amanha": "execute_action{weather(temperature_tomorrow)}",
    "robo vai fazer frio depois de amanha": "execute_action{weather(temperature_aftertm)}",
    "robo vai fazer frio hoje": "execute_action{weather(temperature_today)}",
    "robo vai ficar calor amanha": "execute_action{weather(temperature_tomorrow)}",
    "robo vai ficar calor depois de amanha": "execute_action{weather(temperature_aftertm)}",
    "robo vai ficar calor hoje": "execute_action{weather(temperature_today)}",
    "robo vai ficar frio amanha": "execute_action{weather(temperature_tomorrow)}",
    "robo vai ficar frio depois de amanha": "execute_action{weather(temperature_aftertm)}",
    "robo vai ficar frio hoje": "execute_action{weather(temperature_today)}",
    "seja feliz": "estou feliz execute_action{emotion(happy)}",
    "sera que amanha vai ser frio": "execute_action{weather(temperature_tomorrow)}",
    "sera que amanha vai ser quente": "execute_action{weather(temperature_tomorrow)}",
    "sera que chovera amanha": "execute_action{weather(forecast_tomorrow)}",
    "sera que chovera depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "sera que chovera hoje": "execute_action{weather(forecast_today)}",
    "sera que como esta o clima hoje": "execute_action{weather(forecast_today)}",
    "sera que como esta o tempo hoje": "execute_action{weather(forecast_today)}",
    "sera que como estara o clima amanha": "execute_action{weather(forecast_tomorrow)}",
    "sera que como estara o clima depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "sera que como estara o clima hoje": "execute_action{weather(forecast_today)}",
    "sera que como estara o tempo amanha": "execute_action{weather(forecast_tomorrow)}",
    "sera que como estara o tempo depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "sera que como estara o tempo hoje": "execute_action{weather(forecast_today)}",
    "sera que depois de amanha vai ser frio": "execute_action{weather(temperature_aftertm)}",
    "sera que depois de amanha vai ser quente": "execute_action{weather(temperature_aftertm)}",
    "sera que esta calor hoje": "execute_action{weather(temperature_today)}",
    "sera que esta frio hoje": "execute_action{weather(temperature_today)}",
    "sera que esta quente hoje": "execute_action{weather(forecast_today)}",
    "sera que esta seco hoje": "execute_action{weather(forecast_today)}",
    "sera que esta umido hoje": "execute_action{weather(forecast_today)}",
    "sera que estara calor amanha": "execute_action{weather(forecast_tomorrow)}",
    "sera que estara calor depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "sera que estara calor hoje": "execute_action{weather(temperature_today)}",
    "sera que estara frio amanha": "execute_action{weather(forecast_tomorrow)}",
    "sera que estara frio depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "sera que estara frio hoje": "execute_action{weather(temperature_today)}",
    "sera que estara quente amanha": "execute_action{weather(forecast_tomorrow)}",
    "sera que estara quente depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "sera que estara seco amanha": "execute_action{weather(forecast_tomorrow)}",
    "sera que estara seco depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "sera que estara umido amanha": "execute_action{weather(forecast_tomorrow)}",
    "sera que estara umido depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "sera que fara calor amanha": "execute_action{weather(temperature_tomorrow)}",
    "sera que fara calor depois de amanha": "execute_action{weather(temperature_aftertm)}",
    "sera que fara calor hoje": "execute_action{weather(temperature_today)}",
    "sera que fara frio amanha": "execute_action{weather(temperature_tomorrow)}",
    "sera que fara frio depois de amanha": "execute_action{weather(temperature_aftertm)}",
    "sera que fara frio hoje": "execute_action{weather(temperature_today)}",
    "sera que fara sol amanha": "execute_action{weather(forecast_tomorrow)}",
    "sera que fara sol depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "sera que fara sol hoje": "execute_action{weather(forecast_today)}",
    "sera que hoje vai ser frio": "execute_action{weather(temperature_today)}",
    "sera que hoje vai ser quente": "execute_action{weather(temperature_today)}",
    "sera que nevara amanha": "execute_action{weather(forecast_tomorrow)}",
    "sera que nevara depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "sera que nevara hoje": "execute_action{weather(forecast_today)}",
    "sera que vai chover amanha": "execute_action{weather(forecast_tomorrow)}",
    "sera que vai chover depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "sera que vai chover hoje": "execute_action{weather(forecast_today)}",
    "sera que vai fazer calor amanha": "execute_action{weather(temperature_tomorrow)}",
    "sera que vai fazer calor depois de amanha": "execute_action{weather(temperature_aftertm)}",
    "sera que vai fazer calor hoje": "execute_action{weather(temperature_today)}",
    "sera que vai fazer frio amanha": "execute_action{weather(temperature_tomorrow)}",
    "sera que vai fazer frio depois de amanha": "execute_action{weather(temperature_aftertm)}",
    "sera que vai fazer frio hoje": "execute_action{weather(temperature_today)}",
    "sera que vai fazer sol amanha": "execute_action{weather(forecast_tomorrow)}",
    "sera que vai fazer sol depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "sera que vai fazer sol hoje": "execute_action{weather(forecast_today)}",
    "sera que vai ficar calor amanha": "execute_action{weather(temperature_tomorrow)}",
    "sera que vai ficar calor depois de amanha": "execute_action{weather(temperature_aftertm)}",
    "sera que vai ficar calor hoje": "execute_action{weather(temperature_today)}",
    "sera que vai ficar frio amanha": "execute_action{weather(temperature_tomorrow)}",
    "sera que vai ficar frio depois de amanha": "execute_action{weather(temperature_aftertm)}",
    "sera que vai ficar frio hoje": "execute_action{weather(temperature_today)}",
    "sera que vai nevar amanha": "execute_action{weather(forecast_tomorrow)}",
    "sera que vai nevar depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "sera que vai nevar hoje": "execute_action{weather(forecast_today)}",
    "ta feliz": "estou feliz execute_action{emotion(happy)}",
    "ta normal": "estou normal execute_action{emotion(neutral)}",
    "toca": "execute_action{music()}",
    "toca a musica": "execute_action{music()}",
    "toca uma musica": "execute_action{music()}",
    "tocar": "execute_action{music()}",
    "tocar a cancao": "execute_action{music()}",
    "tocar a musica": "execute_action{music()}",
    "tocar uma cancao": "execute_action{music()}",
    "tocar uma musica": "execute_action{music()}",
    "toque": "execute_action{music()}",
    "toque a cancao": "execute_action{music()}",
    "toque a musica": "execute_action{music()}",
    "toque o som": "execute_action{music()}",
    "toque um som": "execute_action{music()}",
    "toque uma cancao": "execute_action{music()}",
    "toque uma musica": "execute_action{music()}",
    "vai chover agora": "execute_action{weather(forecast_today)}",
    "vai chover amanha": "execute_action{weather(forecast_tomorrow)}",
    "vai chover depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "vai chover hoje": "execute_action{weather(forecast_today)}",
    "vai fazer calor amanha": "execute_action{weather(temperature_tomorrow)}",
    "vai fazer calor depois de amanha": "execute_action{weather(temperature_aftertm)}",
    "vai fazer calor hoje": "execute_action{weather(temperature_today)}",
    "vai fazer frio amanha": "execute_action{weather(temperature_tomorrow)}",
    "vai fazer frio depois de amanha": "execute_action{weather(temperature_aftertm)}",
    "vai fazer frio hoje": "execute_action{weather(temperature_today)}",
    "vai fazer sol amanha": "execute_action{weather(forecast_tomorrow)}",
    "vai fazer sol depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "vai fazer sol hoje": "execute_action{weather(forecast_today)}",
    "vai ficar calor amanha": "execute_action{weather(temperature_tomorrow)}",
    "vai ficar calor depois de amanha": "execute_action{weather(temperature_aftertm)}",
    "vai ficar calor hoje": "execute_action{weather(temperature_today)}",
    "vai ficar frio amanha": "execute_action{weather(temperature_tomorrow)}",
    "vai ficar frio depois de amanha": "execute_action{weather(temperature_aftertm)}",
    "vai ficar frio hoje": "execute_action{weather(temperature_today)}",
    "vai nevar amanha": "execute_action{weather(forecast_tomorrow)}",
    "vai nevar depois de amanha": "execute_action{weather(forecast_aftertm)}",
    "vai nevar hoje": "execute_action{weather(forecast_today)}",
    "vc acha q ta chovendo agora": "execute_action{weather(forecast_today)}",
    "vc acha q vai chover agora": "execute_action{weather(forecast_today)}",
    "voce acha que esta chovendo agora": "execute_action{weather(forecast_today)}",
    "voce sabe a temperatura agora": "execute_action{weather(temperature_today)}",
    "esta quente agora": "execute_action{weather(temperature_today)}",
    "esta frio agora": "execute_action{weather(temperature_today)}",
    "que horas sao": "execute_action{get_time(hour)}",
    "que horas sao agora": "execute_action{get_time(hour)}",
    "que horas e agora": "execute_action{get_time(hour)}",
    "que horas e": "execute_action{get_time(hour)}",
    "que horas que e isso": "execute_action{get_time(hour)}",
    "que horas que sao": "execute_action{get_time(hour)}",
    "que horas sao": "execute_action{get_time(hour)}",
    "que horario e agora": "execute_action{get_time(hour)}",
    "que horario e": "execute_action{get_time(hour)}",
    "que horario": "execute_action{get_time(hour)}",
    "qual horario": "execute_action{get_time(hour)}"
}

def get_best_match(user_question):
    best_match, best_ratio = None, 0
    for question in responses.keys():
        similarity_ratio = SequenceMatcher(None, user_question, question).ratio()
        if similarity_ratio > best_ratio:
            best_match, best_ratio = question, similarity_ratio
    return best_match, best_ratio

def get_chatbot_response(user_question):
    user_question = user_question.strip().lower()

    if user_question in responses:
        return responses[user_question]

    best_match, best_ratio = get_best_match(user_question)
    print(best_ratio)
    if best_ratio >= 0.6:
        return responses[best_match]
    else:
        return "error"

if __name__ == "__main__":
	while 1:
		print(get_chatbot_response(input('Usuário: ')))